### ISSUE TITLE
`register_cmap()` got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by xylar** [rubisco-sfa/ILAMB#40]
ILAMB appears not to be compatible with `matplotlib >= 3.4.0`.  As an example, see [this CI build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=316137&view=logs&jobId=e9afaa34-1a0f-534e-78fc-fae528ccd915&j=e9afaa34-1a0f-534e-78fc-fae528ccd915&t=48395e60-bc5f-5e45-7455-d404f0c95f3a) on conda-forge.

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/ilamb_1620761448485/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/ilamb-run", line 20, in <module>
    if "stoplight" not in plt.colormaps(): RegisterCustomColormaps()
  File "/home/conda/feedstock_root/build_artifacts/ilamb_1620761448485/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/ILAMB/Post.py", line 1030, in RegisterCustomColormaps
    plt.register_cmap(name='stoplight', data=RdYlGn)
TypeError: register_cmap() got an unexpected keyword argument 'data'
```

This feature was apparently deprecated 1 1/2 years ago: https://github.com/matplotlib/matplotlib/pull/15875 in 3.3.0 and was dropped in 3.4.0.

**Comment by xylar** [comment]
It looks like this was fixed in https://github.com/rubisco-sfa/ILAMB/pull/33.  So I guess what I would be asking for is a new release of ILAMB with this fix.

**Comment by nocollier** [comment]
Thanks @xylar, I have been procrastinating a new release for a while now, updated to 2.6 today. I believe that should fix it.

**Comment by xylar** [comment]
Thanks so much!  I'll give that a try tomorrow and close this, assuming all goes well.

**Comment by xylar** [comment]
A simple import test certainly works.  Thank you very much!
