### ISSUE TITLE
AttributeError: module 'matplotlib.cm' has no attribute 'cmap_d'

### ISSUE THREAD

**Issue by chengzhuzhang** [rubisco-sfa/ILAMB#83]
There is an AttributeError: module 'matplotlib.cm' has no attribute 'cmap_d' when running ILAMB v2.6. The relevant log I have as follows:
```
[INFO][0][confront][LeafAreaIndex/eafAreaIndex/AVHRR][20231012.v3alpha04_trigrid_bgc.piControl.chrysalis] Success
[DEBUG][0][WorkPost][LeafAreaIndex/AVHRR][20231012.v3alpha04_trigrid_bgc.piControl.chrysalis]
Traceback (most recent call last):
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.9.0_login/bin/ilamb-run", line 426, in WorkPost
    c.modelPlots(m)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.9.0_login/lib/python3.10/site-packages/ILAMB/Confrontation.py", line 710, in modelPlots
    self._relationship(m)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.9.0_login/lib/python3.10/site-packages/ILAMB/Confrontation.py", line 1153, in _relationship
    _plotDistribution(ref_dist[0],ref_dist[1],ref_dist[2],
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.9.0_login/lib/python3.10/site-packages/ILAMB/Confrontation.py", line 1003, in _plotDistribution
    cmap = 'plasma' if 'plasma' in plt.cm.cmap_d else 'summer')
AttributeError: module 'matplotlib.cm' has no attribute 'cmap_d'
```
I'm wondering if this is a bug specific for v2.6 and earlier?

Thank you!

**Comment by chengzhuzhang** [comment]
It is confirmed that v2.7 resolved above issue.
