### ISSUE TITLE
Errors associated with FLUXCOM/reco.nc and FLUXCOM/gpp.nc

### ISSUE THREAD

**Issue by olyson** [rubisco-sfa/ILAMB#89]
I'm getting errors associated with new versions of FLUXCOM/reco.nc and FLUXCOM/gpp.nc datasets.  I see that the reco and gpp variables in these files are ordered (lat,lon,time) instead of (time,lat,lon), e.g.,

        float gpp(lat, lon, time) ;
                gpp:_FillValue = nanf ;
                gpp:long_name = "GPP" ;
                gpp:units = "g m-2 day-1" ;

I'm wondering if this is what is causing the error.  An example error is:

`[DEBUG][3][WorkConfront][EcosystemRespiration/FLUXCOM][CLM50]
Traceback (most recent call last):
  File "/glade/campaign/cesm/community/lmwg/diag/ILAMB/CODE/ilamb/bin/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/work/oleson/conda-envs/ilamb_casper_lmwg/lib/python3.7/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/work/oleson/conda-envs/ilamb_casper_lmwg/lib/python3.7/site-packages/ILAMB/Confrontation.py", line 376, in stageData
    lons=None if obs.spatial else obs.lon,
  File "/glade/work/oleson/conda-envs/ilamb_casper_lmwg/lib/python3.7/site-packages/ILAMB/ModelResult.py", line 345, in extractTimeSeries
    assert lats.shape == lons.shape
AssertionError`

**Comment by nocollier** [comment]
I ran into this problem and forgot to fix. I re-rendered this data to fix a
nan/fill value issue and in the process messed up the dimensions. Xarray
and future Ilamb won’t care but old ilamb expects dimensions in a given
order.

**Comment by evasinha** [comment]
@nocollier I am getting the same error described above. I am using ILAMB version 2.7. How can I resolve this error?

**Comment by nocollier** [comment]
I just need to fix it, will do now. Stay tuned.

**Comment by nocollier** [comment]
Can you try rerunning ilamb-fetch and checking if the new file resolves the
issue? It looks good on my end.

Nate

**Comment by evasinha** [comment]
@nocollier I ran `ilamb-fetch` in the `DATA` folder . This updated a bunch of files. But when I run ILAMB, I still get the `assert lats.shape == lons.shape AssertionError`.

**Comment by evasinha** [comment]
I ran the ilamb-fetch again and this time it found four updated files related to FLUXCOM. I guess for some reason in the previous ilamb-fetch those updated files were not detected.

**Comment by evasinha** [comment]
@nocollier the updated/new FLUXCOM files have resolved the issue. Thanks for updating the data files.
